import { generateText, LlmRateLimitError } from './llm.js';
import { parseJsonResponse, LlmJsonParseError } from './json.js';
import { isViableJobDescription, type FetchedPage } from './html.js';
import { GENERIC_SIGNALS } from './url-quality.js';

export type LivenessResult = 'dead' | 'alive' | 'unknown';

// High-confidence "this listing is gone" phrasing — a hit here is dead, no LLM needed.
const DEAD_KEYWORDS = [
  /no longer accepting applications/i,
  /position has been filled/i,
  /this job is no longer available/i,
  /this posting has (expired|closed)/i,
  /requisition has been closed/i,
  /vacancy (is |has been )?closed/i,
  /this vacancy no longer exists/i,
  /job (posting )?has been removed/i,
  /page not found/i,
  /job not found/i,
  /job listing not found/i,
  /this job (is no longer|has expired)/i,
  /this job (listing |posting )?(is )?no longer (open|active|posted)/i,
  /posting is no longer active/i,
  /opportunity is no longer available/i,
  /we couldn'?t find (that|this) (job|page|posting)/i,
  /the (job|position|role) you('re| are| were)? looking for (is|could) not be found/i,
  /oops[!.]?\s*(page|job|this)?\s*(not found|couldn'?t be found|doesn'?t exist)/i,
  /this link (is|appears to be) (broken|invalid|no longer valid)/i,
  /http error 404/i,
];

// Softer phrasing that's suggestive but not conclusive — worth an LLM check
// rather than a blind classification either way.
const SOFT_AMBIGUOUS_SIGNALS = [
  /not currently accepting/i,
  /check back (later|soon)/i,
  /similar jobs/i,
  /this role may (no longer|not) be available/i,
  /archived/i,
];

// A page that's actually a bot-block/WAF challenge, not the real posting —
// we have zero signal either way about the job itself, so this must resolve
// to 'unknown', never 'alive' (the current text just happens to clear the
// viability-length bar without being real content at all).
const BOT_BLOCK_SIGNALS = [
  /access denied/i,
  /you don'?t have permission to access/i,
  /request blocked/i,
  /attention required[\s\S]{0,40}cloudflare/i,
  /sorry, you have been blocked/i,
  /enable javascript and cookies to continue/i,
  /unusual traffic from your (computer|network)/i,
  /verify you are (a )?human/i,
  /checking your browser before accessing/i,
  /reference #\s*[\w.]+\.[a-f0-9]+\.\d+/i,
];

// The company's domain has lapsed and been picked up by a registrar/parking
// service, or was never set up past the host's default install page — the
// job (and often the whole company presence at that URL) is definitively
// gone. High-confidence, keyword-only, no LLM needed.
const PARKED_DOMAIN_SIGNALS = [
  /this domain (is|has (recently )?been) (parked|for sale)/i,
  /buy this domain/i,
  /this domain (name )?may be for sale/i,
  /the domain [\s\S]{0,40} is for sale/i,
  /future home of something quite cool/i,
  /this web ?page was generated by the domain owner/i,
  /courtesy of (godaddy|namecheap|dan\.com|sedo|hugedomains)/i,
  /apache2 (ubuntu|debian) default page/i,
  /welcome to nginx!/i,
  /if you are the owner of this (domain|website)[\s\S]{0,40}(please )?(contact|click)/i,
  /this account has been suspended/i,
];

// Content that only shows up when an expired domain has been resold to a
// spam/scam operator — a real job posting will never legitimately contain
// this, so a hit is treated the same as a dead-keyword match.
const SPAM_CONTENT_SIGNALS = [
  /\bonline casino\b/i,
  /\bfree spins\b.{0,30}\bslot/i,
  /\bviagra\b/i,
  /\bcialis\b/i,
  /\bbest online pharmacy\b/i,
  /\b(judi|situs)\s+(slot|togel)\b/i,
];

// English stopwords plus generic job-board filler — excluded so word-overlap
// checks compare on the words that actually distinguish one posting/company
// from another, not just common connective tissue.
const STOPWORDS = new Set([
  'the', 'a', 'an', 'at', 'in', 'of', 'for', 'and', 'or', 'to', 'on', 'is',
  'are', 'with', 'new', 'job', 'jobs', 'role', 'career', 'careers',
]);

export function significantWords(s: string): Set<string> {
  return new Set(
    s
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, ' ')
      .split(/\s+/)
      .filter((w) => w.length >= 4 && !STOPWORDS.has(w))
  );
}

function looksDeadByKeyword(text: string): boolean {
  return DEAD_KEYWORDS.some((re) => re.test(text));
}

function looksAmbiguous(text: string): boolean {
  return SOFT_AMBIGUOUS_SIGNALS.some((re) => re.test(text));
}

function looksBotBlocked(text: string): boolean {
  return BOT_BLOCK_SIGNALS.some((re) => re.test(text));
}

function looksParkedOrSpam(text: string): boolean {
  return (
    PARKED_DOMAIN_SIGNALS.some((re) => re.test(text)) ||
    SPAM_CONTENT_SIGNALS.some((re) => re.test(text))
  );
}

/**
 * True when the page title shares none of the job title's/company's
 * distinguishing words AND the body reads like a generic careers
 * homepage/search page — i.e. we've landed somewhere real but not on the
 * actual posting (a redirected-to-homepage case with no "not found" wording
 * anywhere, so the keyword checks above would otherwise miss it entirely).
 * Requires both signals together to avoid false-positiving on legitimate
 * postings whose <title> is just generic ATS branding.
 */
function looksLikeGenericRedirect(
  pageTitle: string | null,
  bodyText: string,
  title: string,
  company: string
): boolean {
  if (!pageTitle) return false;

  const expectedWords = new Set([...significantWords(title), ...significantWords(company)]);
  if (expectedWords.size === 0) return false;

  const pageWords = significantWords(pageTitle);
  const hasOverlap = [...expectedWords].some((w) => pageWords.has(w));
  if (hasOverlap) return false;

  return GENERIC_SIGNALS.some((re) => re.test(bodyText));
}

interface LlmLivenessResponse {
  status: 'dead' | 'alive';
}

async function checkLivenessByLlm(
  text: string,
  title: string,
  company: string
): Promise<LivenessResult> {
  const prompt = `A job listing for "${title}" at "${company}" links to a page. Below is the page's extracted text (truncated).

Decide: is this listing still open for applications ("alive"), or has it closed/expired/been filled/been removed ("dead")?

PAGE TEXT:
"""
${text.slice(0, 4000)}
"""

Respond with ONLY strict JSON, no other text, no markdown fences:
{"status": "alive"} or {"status": "dead"}`;

  try {
    const raw = await generateText(prompt);
    const parsed = parseJsonResponse<LlmLivenessResponse>(raw);
    if (parsed.status === 'dead' || parsed.status === 'alive') {
      return parsed.status;
    }
    return 'unknown';
  } catch (err) {
    if (err instanceof LlmRateLimitError) {
      console.error(`[dead-listing] ${err.message} — classifying as 'unknown' for this listing`);
    } else if (!(err instanceof LlmJsonParseError)) {
      console.error('[dead-listing] LLM liveness call failed:', err);
    }
    return 'unknown';
  }
}

/**
 * Never returns 'dead' on a mere fetch failure or timeout — only a confident
 * structural signal (malformed URL, 404/410, dead keyword, generic-redirect)
 * or an LLM call can mark a listing dead. Ambiguity always resolves toward
 * 'unknown'/'alive', never toward removal.
 *
 * All of the checks before the LLM fallback are free (no network, no
 * Gemini) and are deliberately ordered cheapest/most-certain first:
 *   1. malformed URL            — never resolves, ever
 *   2. confirmed DNS failure    — the whole domain is gone, not just this page
 *   3. HTTP 404/410             — deterministic "gone" from the server itself
 *   4. dead keyword phrasing    — explicit "closed/filled/expired" wording
 *   5. parked-domain/spam page  — domain lapsed and was resold/parked
 *   6. bot-block/WAF page       — we didn't see the real page at all -> unknown
 *   7. generic-redirect         — landed on a real page, just not this posting
 *   8. soft-ambiguous phrasing  — worth a real LLM judgment call
 */
export async function checkListingLiveness(
  fetched: FetchedPage,
  title: string,
  company: string,
  allowLlm: boolean
): Promise<LivenessResult> {
  if (fetched.malformed) {
    return 'dead';
  }

  if (fetched.dnsFailed) {
    return 'dead';
  }

  if (fetched.status === 404 || fetched.status === 410) {
    return 'dead';
  }

  const fetchedText = fetched.text;
  if (!fetchedText || !isViableJobDescription(fetchedText)) {
    return 'unknown';
  }

  if (looksDeadByKeyword(fetchedText)) {
    return 'dead';
  }

  if (looksParkedOrSpam(fetchedText)) {
    return 'dead';
  }

  if (looksBotBlocked(fetchedText)) {
    return 'unknown';
  }

  if (looksLikeGenericRedirect(fetched.pageTitle, fetchedText, title, company)) {
    return 'dead';
  }

  if (!looksAmbiguous(fetchedText)) {
    return 'alive';
  }

  if (!allowLlm) return 'unknown';

  return checkLivenessByLlm(fetchedText, title, company);
}
